default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end


lane :tests do
  run_tests(
      devices: ["iPhone 13"],
      scheme: "law.handbook"
    )
end

lane :beta do
  increment_build_number(build_number: number_of_commits)

  match(git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"])

  build_ios_app(
      scheme: "law.handbook",
      include_bitcode: true
    )

  app_store_connect_api_key(
      key_id: "2W5Y3ZBD4J",
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
    )

  upload_to_testflight

  commit_version_bump(
    message: "Auto Depoly To Apple Connect By Fastlane",
  )

  push_to_git_remote

end